ARG NODE_VERSION=18
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-alpine as base

WORKDIR /app

FROM base as builder

COPY package.json package.json
COPY lerna.json lerna.json
COPY packages/ packages/
RUN yarn install --frozen-lockfile && yarn lerna bootstrap && yarn build

FROM builder as production
WORKDIR /app/packages/server
EXPOSE $SERVER_PORT
CMD [ "node", "./dist/index.js" ]
