version: "3.9"

services:
  postgres:
    container_name: prakticum-postgres
    image: prakticum-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - prakticum-network
  server:
    container_name: prakticum-server
    image: prakticum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: production
      POSTGRES_HOST: prakticum-postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      API_SERVER_HOST: ${API_SERVER_HOST}
      API_SERVER_PORT: ${API_SERVER_PORT}
    networks:
      - prakticum-network
    depends_on:
      - postgres
  nginx:
    container_name: prakticum-nginx
    image: prakticum-nginx
    build:
        context : .
        dockerfile: Dockerfile.nginx
    depends_on:
      - server
    ports:
      - "80:80"
    restart: always
    networks:
      - prakticum-network

networks:
  prakticum-network:
    driver: bridge 
