version: "3.9"

services:
  postgres:
    container_name: prakticum-postgres
    image: cr.yandex/${CR_REGISTRY}/prakticum-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default
  server:
    container_name: prakticum-server
    image: cr.yandex/${CR_REGISTRY}/prakticum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOST: ${SERVER_HOST}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PRAKTIKUM_HOST: ${PRAKTIKUM_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default
    depends_on:
      - postgres
  nginx:
    container_name: prakticum-nginx
    image: cr.yandex/${CR_REGISTRY}/prakticum-nginx
    build:
        context : .
        dockerfile: Dockerfile.nginx
    depends_on:
      - server
    ports:
      - "80:80"
    environment:
      CR_REGISTRY: ${CR_REGISTRY}
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge 
