ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster-slim as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN yarn build

FROM builder as production
WORKDIR /app/packages/server
EXPOSE $SERVER_PORT
CMD [ "node", "./dist/index.js" ]
