version: "3.9"

services:
  postgres:
    container_name: prakticum-postgres
    image: cr.yandex/${CR_REGISTRY}/prakticum-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - inside
  server:
    container_name: prakticum-server
    image: cr.yandex/${CR_REGISTRY}/prakticum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PRAKTIKUM_HOST: ${PRAKTIKUM_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      API_SERVER_HOST: ${API_SERVER_HOST}
      API_SERVER_PORT: ${API_SERVER_PORT}
    networks:
      - inside
    depends_on:
      - postgres
  certbot:
    container_name: prakticum-certbot
    image: certbot/certbot:latest
    depends_on:
      - server
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - inside
  nginx:
    container_name: prakticum-nginx
    image: cr.yandex/${CR_REGISTRY}/prakticum-nginx
    build:
        context : .
        dockerfile: Dockerfile.nginx
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - inside
      - outside

networks:
  inside:
    name: inside
    driver: bridge
    external: false
  outside:
    name: outside
    driver: bridge
    external: true
