export enum routes {
  Index = '/',
  Login = '/signin',
  Register = '/signup',
  Logout = '/signout',
  GameList = '/game',
  Game = '/game/:chatId',
  Profile = '/profile',
  ProfileId = '/profile/:profileId',
  Leaderboard = '/leaders',
  Forum = '/forum',
  ForumTheme = '/forum/:id',
  E404 = '/404',
  E500 = '/500',
}
