name: Push To Yandex Cloud CR
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Запускает предварительную проверку 
      - uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          # идентификатор регистра
          CR_REGISTRY: crpgk04rnkkeled7bdg1
          # название репозитория
          CR_REPOSITORY: game-crocodile
          IMAGE_TAG: ${{ github.sha }}
          # перееменные среды
          CLIENT_PORT: 3001
          SERVER_PORT: 3000
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: game-crocodile
          POSTGRES_PORT: 5432
          NODE_ENV: development
          POSTGRES_HOST: localhost
          PRAKTIKUM_HOST: ya-praktikum.tech
          API_SERVER_HOST: localhost
          API_SERVER_PORT: 3000
        run: |
          docker compose build
          docker tag prakticum-postgres:latest cr.yandex/$CR_REGISTRY/prakticum-postgres:latest
          docker push cr.yandex/$CR_REGISTRY/prakticum-postgres:latest
          docker tag prakticum-server:latest cr.yandex/$CR_REGISTRY/prakticum-server:latest
          docker push cr.yandex/$CR_REGISTRY/prakticum-server:latest
          docker tag prakticum-nginx:latest cr.yandex/$CR_REGISTRY/prakticum-nginx:latest
          docker push cr.yandex/$CR_REGISTRY/prakticum-nginx:latest
