name: Build And Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Запускает предварительную проверку 
      - uses: actions/checkout@v2
      - name: Login Yandex Cloud
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build and Push
        env:
          # идентификатор регистра
          CR_REGISTRY: crpgk04rnkkeled7bdg1
          # название репозитория
          CR_REPOSITORY: game-crocodile
          IMAGE_TAG: ${{ github.sha }}
          # перееменные среды
          CLIENT_PORT: 3001
          SERVER_PORT: 3000
          POSTGRES_HOST: prakticum-postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: game-crocodile
          POSTGRES_PORT: 5432
          NODE_ENV: production
          PRAKTIKUM_HOST: ya-praktikum.tech
          API_SERVER_HOST: localhost
          API_SERVER_PORT: 3000
          FULL_CHAIN_KEY: ${{ secrets.FULL_CHAIN_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir cert
          echo $FULL_CHAIN_KEY >> ./cert/full_chain.pem
          echo $PRIVATE_KEY >> ./cert/private_key.pem
          docker compose build
          docker push cr.yandex/$CR_REGISTRY/prakticum-nginx:latest
          docker push cr.yandex/$CR_REGISTRY/prakticum-postgres:latest
          docker push cr.yandex/$CR_REGISTRY/prakticum-server:latest
          rm -rf cert
